### ISSUE TITLE
Can't get members of built in groups

### ISSUE THREAD

**Issue by AlexH269** [DirectoryTree/LdapRecord#119]
Hi, it's me again 😃

**Describe the bug**
LdapRecord returns an empty collection, when the members of a built in group are queried. So far I identified two groups where this is happening: "Domänen-Benutzer" and "Domänen-Gäste". My ActiveDirectory is in german and the group names are localized. If I recall correctly the english names are "Domain Users" and "Domain Guests".

**To Reproduce**
See the following code example with comments:
```php
<?php

use LdapRecord\Container;
use LdapRecord\Connection;

require __DIR__ . '/vendor/autoload.php';

$defaultConnection = new Connection([
    'hosts' => ['192.168.1.15'],
    'port' => 389,
    'base_dn' => 'DC=lab,DC=hank-it,DC=com',
    'username' => 'user',
    'password' => 'password',
]);

// Add default connection
Container::addConnection($defaultConnection);

// Works
$group = \LdapRecord\Models\ActiveDirectory\Group::where('samaccountname', '=', 'Rolle1')->first();
$group->members()->get();
$group->members()->recursive()->get();
// Result: Correct group members

// Works
$group = \LdapRecord\Models\ActiveDirectory\Group::where('samaccountname', '=', 'Domänen-Admins')->first();
$group->members()->get();
$group->members()->recursive()->get();
// Result: Correct group members

// Doesn't work
$group = \LdapRecord\Models\ActiveDirectory\Group::where('samaccountname', '=', 'Domänen-Benutzer')->first();
$group->members()->get();
$group->members()->recursive()->get();
// Result: Empty

// Doesn't work
$group = \LdapRecord\Models\ActiveDirectory\Group::find('CN=Domänen-Benutzer,CN=Users,DC=lab,DC=hank-it,DC=com');
$group->members()->get();
$group->members()->recursive()->get();
// Result: Empty

// Doesn't work (with guid of Domänen-Benutzer)
$group = \LdapRecord\Models\ActiveDirectory\Group::findByGuid('2c198331-7f96-4ee8-b370-aee44e1829b9');
$group->members()->get();
$group->members()->recursive()->get();
// Result: Empty

// Doesn't work
$group = \LdapRecord\Models\ActiveDirectory\Group::where('samaccountname', '=', 'Domänen-Gäste')->first();
$group->members()->get();
$group->members()->recursive()->get();
// Result: Empty
```

**Expected behavior**
Return the correct members for the specified builtin groups.

**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.3.3

**Comment by AlexH269** [comment]
I just spun up an AWS Managed AD to test it against an english active directory. The results are consistent with my findings above. The groups "Domain Users" and "Domain Guests" always return empty members.

**Comment by stevebauman** [comment]
Hey @AlexH269, thanks! This isn't actually a bug - but it's something that should be fixed that I'd definitely like to get your feedback on.

Memberships to these groups are stored in a different attribute on users, called `primaryGroupId`. This attribute stores an [RID](https://ldapwiki.com/wiki/Relative%20IDentifier) (Relative Identifier, a sub-section of a full Object SID). 

For example, here is an Object SID for `Domain Users`:

```
S-1-5-2141378235-513
```

And it's relative identifier -- the last sub-section of the Object SID:

```
513
```

You can find these primary group identifiers on Microsofts docs for [Well-known security identifiers](https://support.microsoft.com/en-ca/help/243330/well-known-security-identifiers-in-windows-operating-systems).

> | Object SID | Global Group |
> | --- | --- |
> | S-1-5-21domain-512 | Domain Admins |
> | S-1-5-21domain-513 | Domain Users |
> | S-1-5-21domain-514 | Domain Guests |

Yours will have the same last `513` RID, but contain different characters in the preceding RIDs.

To query for users apart of a primary group (such as `Domain Users`) we would do this:

```php
$domainUsers = User::where('primaryGroupId', '=', '513')->get();
```

Now, the relationship (`members()`) on the `Group` model, queries for all models that contain the groups Distinguished Name inside of their `memberof` attribute. This will likely always return empty for you (as you've shown) unless you have attached *immediate* members to the primary group itself.

We can fix this so a proper query is generated when calling the `members()` relation on a primary group. However, we will likely have to merge both results from the `memberof` query **and** the `primarygroupid` query, so other developers aren't confused as to why direct members of the primary group are not being included.

For this reason, I'm going to work on adding a brand new relationship specifically for merging two relation queries into one. This is how I expect it to work. The below example will run two queries:

- `(memberof=cn=Domain Users,dc=local,dc=com)`
- `(primarygroupid=513)`

```php
$group = Group::findByAnr('Domain Users');

$group->members()->get();
```

Since RID's are the same for all Active Directory instances for these global groups, we can detect if the group is global, and then use an alternate relation. Either that, or we create a `GlobalGroup` model.

What are you thoughts?

**Comment by AlexH269** [comment]
Hi! Thanks for your response and detailed analysis.

If I change a users primaryGroupId to something else, quering the "Domain Users" shows that specific user. This is a rather annoying Microsoft "Feature". 😃

If we use the method you suggested using two queries, one for "memberof" and one for the "primaryGroupId". What about scenarios, where somebody changed the users primaryGroupId? Wouldn't we need to always query for the "memberof" and "primaryGroupId" attribute, regardless of the group? The attribute "primaryGroupToken" holds the id of the group.

**Comment by stevebauman** [comment]
> What about scenarios, where somebody changed the users primaryGroupId? Wouldn't we need to always query for the "memberof" and "primaryGroupId" attribute, regardless of the group?

Good point! You're right -- we will always need to include those regardless.

> The attribute "primaryGroupToken" holds the id of the group.

Yeah, though it's a [computed](https://docs.microsoft.com/en-us/windows/win32/adschema/a-primarygrouptoken) property, so I want to avoid using that if possible.

**Comment by stevebauman** [comment]
Okay, just pushed an update. Whenever you can, could you try `dev-master` and let me know your thoughts? :smile:

**Comment by AlexH269** [comment]
Thanks! Will do first thing tomorrow :)

**Comment by stevebauman** [comment]
Awesome! Thanks for your help on this @AlexH269! Much appreciated 👍

**Comment by AlexH269** [comment]
Hi!

Great job with the commit. Nice idea to parse the sid (avoding the primaryGroupToken) and then matching it onto the primarygroupid. From what i could test, it works quite well, including users who have a non default primary group. So my original "Problem" is fixed.

Why would it have been a problem to use the computed property though?

**Comment by stevebauman** [comment]
Thanks @AlexH269!

> Why would it have been a problem to use the computed property though?

From what I tested, this particular computed property must be manually selected, otherwise it won't be returned from Active Directory. For example:

```php
// Will not include 'primaryGroupToken'
$group = Group::first();

// Will include 'primaryGroupToken'
$group = Group::first(['*', 'primaryGroupToken']);
```

So this posed problems if someone didn't have them added into selects and requested the primary groups members:

```php
// Will not include primary group members:
$group = Group::first();
$group->members()->get();

// Will include primary group members:
$group = Group::first(['*', 'primaryGroupToken']);
$group->members()->get();
```

**Comment by stevebauman** [comment]
Completed 🎉 . New release will be out shortly @AlexH269! Thanks again for your input and help on this 😄

**Comment by AlexH269** [comment]
The same issue also exists, when retrieving the inverse relationship, e.g.

````php
$user->groups()->get()
````

Can we appliy the same fix?

I can also create a dedicated issue, if necessary :)

**Comment by stevebauman** [comment]
Oh shoot thanks @AlexH269! Would you mind creating another issue so I can track it?

**Comment by stevebauman** [comment]
Never mind! All done. New release will be out today 👍
