### ISSUE TITLE
Active Directory authentication differences with Adldap2

### ISSUE THREAD

**Issue by ckieffer** [DirectoryTree/LdapRecord#131]
I'm testing the move of Adldap2-based AD authentication code over to LdapRecord. I really miss the account_suffix option and $bindAsUser option. Any chance that they'll be added?

**Comment by stevebauman** [comment]
Hi @ckieffer!

`$bindAsUser` is still there:

https://ldaprecord.com/docs/connections/#binding

```php
$user = 'cn=user,dc=local,dc=com';
$password = 'secret';

if ($connection->auth()->attempt($user, $password, $bindAsUser = true))
{
    echo "Username and password are correct!";

    // Run further LDAP operations under this user.
}
```

Also, the `account_suffix` and `account_prefix` options have been removed since you can simply append or prepend these onto usernames yourself:

```php
$suffx = '@local.com';
$user = 'jdoe';
$password = 'secret';

if ($connection->auth()->attempt($user.$suffix, $password, $bindAsUser = true))
{
    //
}
```

I'll close this as the above should resolve your issue -- but please comment back if you need any further assistance and I'd be glad to help! :smile:

**Comment by ckieffer** [comment]
Thanks. I just didn't see this type of example or mention of the bindAsUser option [in the docs](https://ldaprecord.com/docs/authentication/). 

I've completed the migration. Thanks again for your work on this.

**Comment by stevebauman** [comment]
Thanks @ckieffer! Appreciate the kind words ❤️
