### ISSUE TITLE
Pagination with openldap does not seem to have any effect

### ISSUE THREAD

**Issue by mgiritli** [DirectoryTree/LdapRecord#240]
**Environment (please complete the following information):**
 - LDAP Server Type: openldap
 - PHP Version:7.4

directorytree/ldaprecord             v1.12.4   A fully-featured LDAP ORM.
directorytree/ldaprecord-laravel     v1.7.6    LDAP Authentication & Management for Laravel.

I'm using ldaprecord for a while now and just recently needed to use pagination feature for the first time. However, when I use paginate(n) method, it dosesn't seem to have any effect. Instead of returning n records, it returns all of the records. 

Here is a code snippet :
    	$users = Entry::in($baseDN)
                                ->where("objectclass", "=", "KAMUNETMakineKullaniciKontrolSinifNesnesi")
                                ->orWhere( "objectclass", "=", "KAMUNETKullaniciKontrolSinifNesnesi")
                                ->select("modifyTimestamp", "modifiersName", "createTimestamp", "creatorsName","entryuuid","sn","givenName","cn","uid","mail","kamunetaktifhesap","kamunetsuperkullanici", "description")
->paginate(10);

dd($users) will now return all of the users (100s of them) instead of 10. How do I start gathering more debug information on this?

In the logs I see:

[2021-02-09 13:05:56] local.INFO: LDAP (ldap://...:389) - Operation: Paginate - Base DN: ou=...- Filter: (|(objectclass=KAMUNETMakineKullaniciKontrolSinifNesnesi)(objectclass=KAMUNETKullaniciKontrolSinifNesnesi)) - Selected: (modifyTimestamp,modifiersName,createTimestamp,creatorsName,entryuuid,sn,givenName,cn,uid,mail,kamunetaktifhesap,kamunetsuperkullanici,description,objectclass) - Time Elapsed: 400.99

So it does detect pagination but the result is not paginated.

**Comment by stevebauman** [comment]
Hi @mgiritli,

This is intended. Unfortunately PHP's LDAP extension does not support the ability to iterate through "pages" of LDAP objects, because it does not allow you to re-use pagination cookies on subsequent HTTP requests.

This is highlighted in the LdapRecord docs:

https://ldaprecord.com/docs/core/v2/searching/#paginating

---

<img width="782" alt="Screen Shot 2021-02-09 at 12 15 23 PM" src="https://user-images.githubusercontent.com/6421846/107401046-7d212c80-6ad0-11eb-9f91-327b78a136db.png">

---

You will either have to:

- Implement a tree-like view for your LDAP directory.
- Break the LDAP results into pages manually and extend/implement your own Laravel `LengthAwarePaginator`.

Hope this helps!

Let me know if you have any further questions 👍
