### ISSUE TITLE
A way to disable ssl certificate validation

### ISSUE THREAD

**Issue by abublihi** [DirectoryTree/LdapRecord#284]
I am having problem with tls/ssl connection. so is there any configuration to disable the validation of the certificate?

I have tried `TLS_REQCERT never` in `etc/ldap/ldap.conf` but not working

**Comment by abublihi** [comment]
I have a workaround which is `putenv('LDAPTLS_REQCERT=never');` and that worked for me.

This is not to close the issue but we want some option to disable the validation of the certificate for example in the config file.

**Comment by stevebauman** [comment]
HI @abublihi! Thank you so much for your sponsorship ❤️ 

Did you restart your web server after making changes to the `ldap.conf` file?

If the above procedure doesn't work for disabling certificate verification, then as you've discovered, the only way around this would be to use `putenv('LDAPTLS_REQCERT=never')`, or acquire a valid certificate and place it on your web sever.

I think you have a point though, this could be an option added into the configuration -- however, if we did do that, any subsequent LDAP connections created during the same request would have their certificate verification disabled as well, which could potentially be a security issue. This is because we can't (to my knowledge) disable certificate verification *per LDAP connection*.

We could perhaps make this a callable function with the connection `Container`, for example:

```php
use LdapRecord\Container;

Container::getInstance()->disableCertificateVerification();
```

What are your thoughts?

**Comment by abublihi** [comment]
Thank you for your quick response.

No I did not restart the server, after trying that it was working fine.

`disableCertificateVerification` function would be a good option.

Thank you.
