### ISSUE TITLE
Ldap laravel with Active Directory

### ISSUE THREAD

**Issue by MajoP27** [DirectoryTree/LdapRecord#312]
Hola estoy implementando tu tutorial pero no logro conectarme, no me da ningún error al ingresar las credenciales, en consola solo veo un error 302 Not found. Por favor tu ayuda estoy trabajando con laravel 8 y sql server 2019.

**Comment by stevebauman** [comment]
Hi @MajoP27,

I'm sorry, but due to my own time restrictions, I can now only support users who have sponsored me on GitHub. I've updated the [readme](https://github.com/DirectoryTree/LdapRecord-Laravel/blob/master/readme.md) to reflect this change:

> LdapRecord-Laravel is Supportware™
If you require support using LdapRecord-Laravel, a sponsorship is required 🙏

Thank you for your understanding :heart:
