### ISSUE TITLE
Search returning empyt when it is done by model in Laravel

### ISSUE THREAD

**Issue by efcjunior** [DirectoryTree/LdapRecord#482]
Library v2.

I made connection configuration in .env file of Laravel 8. 

This way it word properly: 

`$connection = Container::getDefaultConnection();
        $results = $connection->query()->where('uid', '=', '99999')->get();`

But in this another way it is working:

`        $users = User::where('uid', '=', '99999')->get();
`

I got this result:

`object(LdapRecord\Models\Collection)#318 (2) { ["items":protected]=> array(0) { } ["escapeWhenCastingToString":protected]=> bool(false) }`

What have I done wrong?

**Comment by stevebauman** [comment]
Hi @efcjunior,

Please fill out the required information when submitting an issue. If this is not filled out, I cannot help you properly.

However, by the looks of it, you're likely connecting to an OpenLDAP server, but are using an `ActiveDirectory\User` model.

Make sure you're using the correct built-in model (or create your own), otherwise, you will not retrieve results.

```php
use LdapRecord\Models\OpenLDAP\User;

$users = User::where('uid', '=', '99999')->get();

dd($users);
```
