### ISSUE TITLE
[Bug] hasMany() doesn't filter by objectClass

### ISSUE THREAD

**Issue by reind33r** [DirectoryTree/LdapRecord#484]
**Environment:**
 - LDAP Server Type: OpenLDAP /
 - PHP Version: 8

**Describe the bug:**

When defining a hasMany() relationship through model class (e.g. the User class in the doc), the query filter used to retrieve the groups doesn´t care about the objectClass of the related model.

```php
<?php

use LdapRecord\Models\Model;

class User extends Model
{
    /**
     * Retrieve the groups the user is apart of.
     */
    public function groups()
    {
        return $this->hasMany(Group::class, 'member');
    }
}
```

i.e. calling `$user->groups()->get()` will yield such search: `(member=cn\3dJohn Doe\2cdc\3dacme\2cdc\3dorg)`.

I would expect the query to be constructed in a way that only entries matching the `Group` model $objectClasses are retrieved.

Use-case: if one LDAP setup uses two separate object classes with the same attribute `member` (let's say `group` and for instance, `school`), then $user->groups() will return both group and school entries for the user.

**Bug or feature?**

The documentation mentions this behaviour implicitly ("For example, this is the query filter that will be used in the search: ..."). I believe maybe it should mention explicitly that objectClasses are not taken into account, if this is the desired behaviour.

I am quite new to LDAP so maybe the use-case I mentioned (group, school both using a member attribute) is not a good practice. If this is the case, please forgive me! :D

**Comment by stevebauman** [comment]
Hi @reind33r! This is a great question.

> Use-case: if one LDAP setup uses two separate object classes with the same attribute member (let's say group and for instance, school), then $user->groups() will return both group and school entries for the user.

You're right -- this would occur. However, `$objectclasses` are taken into account when building the models *from* a relationship query result. This means that you will receive both the `group` and `school`, but the `school` will be returned as an `Entry` instance, and not a `Group` instance, since it's `$objectclasses` would not match the `Group::$objectClasses`:

```php
$groups = $user->groups()->get();

// [
//     0 => Group:class,
//     1 => Entry::class,
// ]
dd($groups);
```

If you want to scope the relation by the object classes from the model instance, you can do:

```php
 public function groups()
{
    return $this
            ->hasMany(Group::class, 'member')
            ->whereIn('objectclass', Group::$objectClasses);
}
```

The reason I don't take object classes into account for the relationship query, is particularly due to the inverse the membership you've shown above:

```php
class Group extends Model
{
    public function members()
    {
        return $this->hasMany(User::class, 'memberof');
    }
}
```

If we took the above relationship and scoped it to the `User::$objectClasses`, developers would not receive any results for any members that have any additional (or missing) objectclasses on their member objects. They can instead provide an array of *possible* member models, that will be represented in the relation result (as shown above).

I think relations should be as open as possible to prevent confusion. If I modified this (even with proper documentation), I would certainly get many issues of users whom are not receiving results from relation queries.

**Comment by reind33r** [comment]
Hi!

Thank you for the very detailed answer!

It makes sense, and it is indeed easy to filter the results if required, like you suggested. I guess if anyone else gets surprised by this, they'll find your explanation here easily.

Great work on this project, it's been working very smoothly!

**Comment by stevebauman** [comment]
Happy to help @reind33r! Like you mentioned, this would be good to put into the docs so others aren't caught off guard, as it certainly can be misleading.

Thanks for your kind words! I'm glad you enjoy using LdapRecord 😄
