### ISSUE TITLE
Saved getModifications

### ISSUE THREAD

**Issue by vatsake** [DirectoryTree/LdapRecord#507]
In the event "saved", there currently isn't any way to know what changed.
I don't want to use "saving" events, because maybe for some reason saving fails?

**Comment by stevebauman** [comment]
Hi @vatsake,

This is intended, and operates the same as Laravel's Eloquent. I actually submitted a PR to Laravel for this feature, but it was denied for a good-cause, as the memory usage could be significant depending on how many models are updated in the lifetime of one request, since we would be storing a copy of all previous attributes after a model has been saved:

https://github.com/laravel/framework/pull/42504

You would have to implement this yourself but registering a listener on the `updated` event as shown in the above PR, and then keep a copy of the modifications locally.

Something like this should get you started:

```php
use LdapRecord\Models\ActiveDirectory\User;

class User extends BaseUser
{
    protected $previous;

    /**
     * The "boot" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        static::updating(function (User $user) {
            $user->syncPrevious();
        })
    }

    /**
     * Sync the users previous modifications.
     *
     * @return void
     */
    public function syncPrevious()
    {
        $this->previous = $this->getModifications();
    }
}
```

Let me know if you have any other questions 👍

**Comment by stevebauman** [comment]
Happy to help @vatsake!

> Are you sure it doesn't exist in Laravel (maybe they delete if after saved event)? I just checked my different project, I have in my model:

This works because you're accessing the changes directly inside of the `updated` event -- but you won't be able to access them outside of that event after a `save()`, as they are reset.

Ex:

```php
$user->name = 'Foo';

$user->getChanges(); // ['name' => 'Foo']

$user->save();

$user->getChanges(); // Returns empty array.
```

You can actually do the same thing in LdapRecord as your above example if you'd like 👍
