### ISSUE TITLE
[Bug] Events not firing when updating groups

### ISSUE THREAD

**Issue by vatsake** [DirectoryTree/LdapRecord#508]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version:  8.1

**Describe the bug:**
Modifying an AD group does not trigger saved/saving/updated/updating event.

**Comment by stevebauman** [comment]
Hi @vatsake, can you share your code?

**Comment by stevebauman** [comment]
Gotcha, thanks for posting that @vatsake! You're right -- this is a bug.

We're currently using the `$model->createAttribute()` method to add members to groups:

https://github.com/DirectoryTree/LdapRecord/blob/3e5af5583a4d7f68f54d90d97183fd32ae1bc7c7/src/Models/Relations/HasMany.php#L256

But this method does not fire any `updated` events:

https://github.com/DirectoryTree/LdapRecord/blob/3e5af5583a4d7f68f54d90d97183fd32ae1bc7c7/src/Models/Model.php#L1234-L1241

Going to patch this -- thanks for the report! 🙏

**Comment by stevebauman** [comment]
Hi @vatsake, a new release has just been created with a patch for this. Thanks again 👍 

https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.17.3

**Comment by stevebauman** [comment]
@vatsake Do you mean modifying group membership? In this case, there are no batch modifications added to the model, due to the relation using `$model->createAttribute()` (during group membership `attach()` or `$model->deleteAttribute()` (during a group membership `detach()`).

These method submit an attribute with a value for creation/deletion directly to the LDAP server (shown in the above comment). This is done due to performance concerns. Using a batch modification to add/remove users from groups requires the submission of the entire group membership list, excluding or including the added/removed user, depending on the operation. Using `createAttribute()` or `deleteAttribute()` bypasses this performance issue, and requires no group membership list to be sent -- only the attaching/detaching user.

`$model->getModifications()` will return any manually added batch modifications along with generating batch modifications from the models original-vs-modified attributes.

Hope this answers your question!
