### ISSUE TITLE
[Bug] findByOrFail returns Model or array

### ISSUE THREAD

**Issue by NicolasCARPi** [DirectoryTree/LdapRecord#567]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 8.1

**Describe the bug:**

The function `findByOrFail` should return `Model` but returns `Model|array`.

That's because `firstOrFail` returns possibly an array: https://github.com/DirectoryTree/LdapRecord/blob/517c6bc535fd6ef17b0848f5c93db6f84beebccf/src/Query/Builder.php#L812

But the `@return` annotation says it returns a `Model` which is wrong.

In my case it returns an array, which is unexpected, I want a Model!

You can find this sort of issue with phpstan:

` phpstan analyse src --level 7`
`Method LdapRecord\Query\Builder::findByOrFail() should return LdapRecord\Models\Model but returns array|LdapRecord\Models\Model.`

I believe you should completely remove the possibility of returning an array, your Model object is great and that's what should always be returned.

Side note: I'm wondering why you're not using typed arguments/return types instead of annotations.

**Comment by stevebauman** [comment]
Hi @NicolasCARPi,

> I believe you should completely remove the possibility of returning an array, your Model object is great and that's what should always be returned.

This is not a bug, because the `Query\Model\Builder` extends the `Query\Builder`, but the model builder does not override the `findOrFail()` method.

This means, when a `Model` is used for a query, a `Model` instances are **always** returned. If a raw query is being used, an array will be returned. The documented return type has been adjusted to provide type hints for either case, so that they are correct.

**Model Query**:

```php
use LdapRecord\Models\ActiveDirectory\User;

// instanceof \LdapRecord\Models\ActiveDirectory\User
User::firstOrFail();
```

**Raw Connection Query**:

```php
use LdapRecord\Connection;

$connection = new Connection(['...']);

$connection->query()->firstOrFail(); // array
```

> Side note: I'm wondering why you're not using typed arguments/return types instead of annotations.

Being added in v3 👍

**Comment by NicolasCARPi** [comment]
Hello Steve.

Ok after drilling down the doc a bit more and thanks to your explanation I was able to achieve what I wanted and use a `Model`.

Cheers,
~Nico
