### ISSUE TITLE
[Support] IS there any demo app for this plugin?

### ISSUE THREAD

**Issue by MaciejSuchanski** [DirectoryTree/LdapRecord#577]
Is there any demo app source code? The on that will only need a AD basic config filled and will work? I struggle to make anything working myself :(

**Comment by ajibarra** [comment]
It would help if you attach your current config so we can see if there is anything wrong with it.

**Comment by MaciejSuchanski** [comment]
Things i don't know how to do:
1. use firstName.lastName username, not FirstName LastName,
2. make a session or block access to all other pages without loggin in first,
3. destroy that session after log out or some time or browser close.
Code below, i use laravel 10 for frontend and backend (this does log me in):
       
        $attributes = request()->validate([
            'username' => 'required',
            'password' => 'required',
        ]);

        $u = $attributes['username'];
        $p = $attributes['password'];

        $new_u = ucwords(Str::replace('.', ' ', $u));

        $connection = new Connection([
            'hosts'    => ['192.168.1.1']
        ]);

        if ($connection->auth()->attempt($new_u, $p, $stayBound = true)) {
            return redirect('/wyslij')->with('success', 'Logged!');
        } else {
            return redirect('/zaloguj')->with('success', 'Bad username or password!');
        }

**Comment by ajibarra** [comment]
I cannot help with Laravel stuff because I don't use it but maybe somebody else can help you with it. You could give a try to [CakePHP](https://cakephp.org) which usually makes things a lot easier.

On the other hand I see you are using $connection->auth directly. I would create connection and then call $connection->connect() to finally add the connection to the Container (LdapRecord\Container) which would allow you to actually execute queries over LDAP etc (i.e getting all logged in user attributes)

About the point 1 I think @stevebauman have clarified that on #572

**Comment by MaciejSuchanski** [comment]
Laravel is a requirement, tried #572 but it does nothing, i don't understand what that should do. Username is passed exacly the same as the one i type.

        $attributes = request()->validate([
            'username' => 'required',
            'password' => 'required',
        ]);

        $u = $attributes['username'];
        $p = $attributes['password'];

        $escaped = (new EscapedValue($u))->dn();

        $connection = new Connection([
            'hosts'    => ['192.168.118.1']
        ]);

        dd($escaped);
        
        if ($connection->auth()->attempt($escaped, $p, $stayBound = true)) {
            return redirect('/wyslij')->with('success', 'Zalogowany!');
        } else {
            return redirect('/zaloguj')->with('success', 'Błędne dane!');
        }

**Comment by ajibarra** [comment]
Could you try $connection->connect($username,$password) and paste here the result?

**Comment by stevebauman** [comment]
Hi @MaciejSuchanski,

I don't provide starters, as everyone has their own preferences of what Laravel starter kit should be used and how it should be implemented. I would also likely receive requests for variations of those starters (Laravel Breeze, Laravel JetStream, Laravel Auth, Plain Laravel), and I wouldn't have the time to maintain these.

If you're looking for something simple to get started with, I would recommend starting a small demo project with [Laravel UI](https://github.com/laravel/ui) with the Bootstrap scaffolding, even though it's older than Breeze and Jetstream. It's very straightforward to get up and running with very little compilation steps and a simpler backend structure. I have a step-by-step guide for Laravel UI in the documentation here:

https://ldaprecord.com/docs/laravel/v2/auth/database/laravel-ui#introduction

Laravel Breeze and Jetstream include a lot of functionality out-of-the-box, but may cause confusion for a newcomer to the Laravel due to all their files, options, and compilation steps.

I hope this helps! Good luck! 🙏
