### ISSUE TITLE
[Bug] Group-Attach might be broken in OpenLDAP

### ISSUE THREAD

**Issue by EifX** [DirectoryTree/LdapRecord#596]
**Environment:**
 - LDAP Server Type: OpenLDAP on Ubuntu 22.04
 - PHP Version: 8.2
 - LdapRecord: 2.20.3

**Describe the bug:**

Example-Code:
```php
$user = (new User)->findByGuidOrFail("A valid guid");
$group = (new Group)->findByOrFail('cn', "A valid group name");
$group->members()->attach($user);
```

If I run this code, I will get the following error:
_LdapRecord\LdapRecordException: ldap_mod_add(): Modify: Object class violation_
_attribute memberUid not allowed_

I dig deeper in the LdapRecord-Code and I found the issue in File "Ldap.php" - Line 371.

```php
//[..]
return $this->executeFailableOperation(function () use ($dn, $entry) {
            return ldap_mod_add($this->connection, $dn, $entry);
        });
//[..]
```

**$dn** contains the User's dn
**$entry** contains an array with the following content: ["memberUid" => ["Group's dn"]]

I would say, that the content from $dn and $entry is switched. $dn should contain the Group's dn and $entry should contain ["memberUid" => ["User's dn"]]

**Comment by stevebauman** [comment]
Hi @EifX,

Can you please post the LdapRecord models you’re using?

**Comment by EifX** [comment]
Hi @stevebauman,
I am using the OpenLDAP-Standard-Models:

- LdapRecord\Models\OpenLDAP\User
- LdapRecord\Models\OpenLDAP\Group

A little modifications I have made. My Group:
```php
use LdapRecord\Models\OpenLDAP\Group;
class OpenLDAPGroup extends Group
{
    public static $objectClasses = [
        'top',
        'posixgroup',
    ];
}
```

My User:
```php
use LdapRecord\Models\OpenLDAP\User;

class OpenLDAPUser extends User
{
    public static $objectClasses = [
        'top',
        'posixaccount',
        'inetorgperson',
    ];

    public function getCreatableRdn($name = null, $attribute = null)
    {
        return parent::getCreatableRdn(null, 'uid');
    }
}
```

**Comment by stevebauman** [comment]
Hi @EifX,

The `posixGroup` object class cannot be used with the included `OpenLDAP\Group` and `OpenLDAP\User` models and their default relationships. This is because `posixGroup`'s can only contain user UID's and not distinguished names.

You must create your own `User` and `Group` model that extend the `OpenLDAP\Entry` class, and redefine the relationships like so:

**Group Model**:

```php
use LdapRecord\Models\OpenLDAP\Entry;

class OpenLDAPGroup extends Group
{
    public static $objectClasses = [
        'top',
        'posixgroup',
    ];

    public function users()
    {
        return $this->hasManyIn(OpenLDAPUser::class, 'memberuid', 'uid');
    }
}
```

**Important**: The `hasManyIn` relationship as shown above does not currently have `attach` or `detach` methods. You must use the `createAttribute` and `deleteAttribute` methods to attach or detach users when iterating with `OpenLDAPGroup` models:

```php
$group = OpenLDAPGroup::find('...');

// Attaching a user...
$group->createAttribute('memberuid', $user->getFirstAttribute('uid'));

// Detaching a user...
$group->deleteAttribute(['memberuid' => $user->getFirstAttribute('uid')]);
```

These have been added in v3.0 which will be released in the coming weeks.

**User Model**:

```php
use LdapRecord\Models\OpenLDAP\Entry;

class User extends Entry
{
    public static array $objectClasses = [
        'top',
        'posixAccount',
        'inetOrgPerson',
    ];

    public function groups(): HasMany
    {
        return $this->hasMany(Group::class, 'memberuid', 'uid');
    }
}
```

The above implementations should work as I've tested them with my own local OpenLDAP server. If you have issues, ping me back and I can assist you further 👍
