### ISSUE TITLE
[Bug] Missing type declaration at Builder::prepareWhereValue()

### ISSUE THREAD

**Issue by mirkoschmidt** [DirectoryTree/LdapRecord#618]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1

**Describe the bug:**
The return type declaration of the method "prepareWhereValue" (LdapRecord\Query\Builder & LdapRecord\Query\Model\Builder) is not complete. It only expected string but in some case it returned "LdapRecord\Models\Attributes\EscapedValue" if $raw is false.

`return $raw ? $value : $this->escape($value);`
https://github.com/DirectoryTree/LdapRecord/blob/v3.0.6/src/Query/Builder.php#L960
https://github.com/DirectoryTree/LdapRecord/blob/v3.0.6/src/Query/Model/Builder.php#L384

It only need an extend of the return type declaration.

**Comment by stevebauman** [comment]
Hi @mirkoschmidt,

The return type is intentional. The `EscapedValue` class contains a `__toString()` method that will automatically be invoked due to the `string` return type:

https://github.com/DirectoryTree/LdapRecord/blob/3e69c09071f40fdad80f4b9f2adce9b24a1624cd/src/Models/Attributes/EscapedValue.php#L44-L50

What you're describing would only be the case if `declare(strict_types=1)` was added at the top of the file.
