### ISSUE TITLE
LDAP_HOST only one server

### ISSUE THREAD

**Issue by pincopallino2015** [DirectoryTree/LdapRecord#622]
Hello,
If I set two domain controllers in the LDAP_HOST variable I get this error message:
Cannot assign array to property LdapRecord\Connection::$host of type string.
If I declare the $host property in the Connection class as an array or nothing like the old 2.x version everything works fine

**Comment by stevebauman** [comment]
Hi @pincopallino2015, do you mean the `LDAP_HOST` environment variable?

If so, this is because the `hosts` value is already wrapped inside of an array. You must reformat the `ldap.php` config file `hosts` value to the below structure:

https://github.com/DirectoryTree/LdapRecord-Laravel/blob/98e8c4e5f38a006f09f7f86ce290228881e043b1/config/ldap.php#L32

```diff
<?php

return [
    'connections' => [

        'default' => [
-            'hosts' => [env('LDAP_HOST', '127.0.0.1')],
+            'hosts' => explode(',', env('LDAP_HOST', '127.0.0.1')),
            // ...
        ],

    ],

    // ...
];
```

Then, inside your `.env`, you can comma separate your hosts to use multiple:

```env
LDAP_HOST=127.0.0.1,127.0.0.2
```

Let me know if that works for you 👍

**Comment by pincopallino2015** [comment]
Thanks a lot @stevebauman,
now it works.
👍

**Comment by stevebauman** [comment]
Excellent! Thanks for following up @pincopallino2015 👍
