### ISSUE TITLE
[Support] The way the document is proposed to be used doesn't actually work?

### ISSUE THREAD

**Issue by yesee-yongb-xu** [DirectoryTree/LdapRecord#642]
**Environment:**
 - LDAP Server Type: OpenLDAP 
 - PHP Version: 8.1
https://ldaprecord.com/docs/core/v3/connections#container
I use this function Container::getDefaultConnection(), but my editor complains that it is not a static method.
What should I do?

Thank,you!

**Comment by stevebauman** [comment]
Hi @yesee-yongb-xu! This is intentional.

The `Container` class utilizes magic methods to allow you to call static methods on its global instance without retrieving the instance first:

https://github.com/DirectoryTree/LdapRecord/blob/cb671ac72940838fa4d1253f8615226ebe3ba7cf/src/Container.php#L42-L48

If you want type-hints from your editor, you may use:

```php
use LdapRecord\Container;

Container::getInstance()->getDefaultConnection();
```
