### ISSUE TITLE
[Bug] Cannot set account control

### ISSUE THREAD

**Issue by vatsake** [DirectoryTree/LdapRecord#645]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - LdapRecord-Laravel Major Version: v3.0.7
 - PHP Version: 8.1.6

**Describe the bug:**
Ehm.. Am I doing something wrong here?

```
$users = User::query()
  ->whereRaw('userAccountControl:1.2.840.113556.1.4.803:', '!', 2) // Not disabled
  ->get();
/** @var \LdapRecord\Query\Collection<int, User>*/
$users = User::filter($users); //Excludes specific DN

foreach ($users as $user) {
    $uac = $user->accountControl()
    $user->userAccountControl = $uac->unsetFlag(AccountControl::ACCOUNTDISABLE);

    dd($user->accountControl());
}
```
`
  LdapRecord\Models\Attributes\AccountControl::__construct(): Argument DirectoryTree/LdapRecord-Laravel#1 ($flag) must be of type ?int, LdapRecord\Models\Attributes\AccountControl given, called in ...\vendor\directorytree\ldaprecord\src\Models\ActiveDirectory\User.php on line 91`

**Comment by stevebauman** [comment]
Thanks @vatsake! I'm able to replicate this.

This is occurring because you're setting the `userAccountControl` attribute to the `AccountControl` instance (which should certainly be allowed), and then calling `$user->accountControl()` is attempting to create a new `AccountControl` object with the existing `AccountControl` instance:

https://github.com/DirectoryTree/LdapRecord/blob/b433ddd295610300e69b3f8bd2e452c9ef29eef2/src/Models/ActiveDirectory/User.php#L88-L93

I have a patch out for this: https://github.com/DirectoryTree/LdapRecord/pull/646

Once the tests pass I will merge and release the fix 👍

**Comment by stevebauman** [comment]
Patch is out! Please run `composer update` and you're all set.

Thanks for the report @vatsake!
