### ISSUE TITLE
Pagination Issue: Not able to fetch more than 1000 Users from AD LDAP 

### ISSUE THREAD

**Issue by fawwashkhan** [DirectoryTree/LdapRecord#743]
Environment:
LDAP Server Type: ActiveDirectory
PHP Version: PHP 8.2

```
private function handleAdLdapUsersEx($provider): void
{
    try {
        $pageSize = 500;

        if ($this->searchBase->filter) {
            $provider->where($this->searchBase->filter);
        }

        $pagedUsers = $provider->select('distinguishedname', 'givenname', 'name', 'objectguid', 'samaccountname', 'userprincipalname', 'mail')
            ->whereEnabled()
            ->paginate($pageSize, $this->currentPage);
        
        dump($pagedUsers->count());
        
        if ($pagedUsers->count() > 0) {
            collect($pagedUsers->getResults())->chunk(500)->each(function ($chunkedUsers) {
                $this->handleBulk($chunkedUsers);
                unset($chunkedUsers);
                gc_collect_cycles();
            });

            if ($pagedUsers->count() === $pageSize) {
                ImportUsersJob::dispatch($this->searchBase, $this->ldapConnector, $this->ldapConfig, $this->currentPage + 1);
            }
        }
    } catch (\Exception $e) {
        dd($e->getMessage());
    }
}
```

I am currently working on a recursive job to import over 20,000 users. I'm using pagination to fetch 500 users per page; however, it is retrieving all users on a single page, which is causing a timeout issue.

Here is the existing issue: https://github.com/DirectoryTree/LdapRecord/issues/315
Note: The existing issue was raised in PHP 7.4.10
PHP 7.4.10 supports ldap_control_paged_result and ldap_control_paged_result_response but it got DEPRECATED in PHP 7.4.0, and REMOVED in PHP 8.0.0.

Also I am attaching my stack overflow question for more details, [Link is here](https://stackoverflow.com/questions/79129992/how-to-fetch-all-users-from-ad-ldap-in-laravel-without-timeout-or-memory-issues)

Any advice on managing large result sets in PHP 8.2 would be greatly appreciated! @stevebauman

**Comment by stevebauman** [comment]
Hi @fawwashkhan, I'm a little confused with the title and description of this issue. This issue is titled: 

> Not able to fetch more than 1000 Users from AD LDAP

But then you mention:

>  I'm using pagination to fetch 500 users per page; however, it is retrieving all users on a single page, which is causing a timeout issue.

So I'm unsure if you're actually receiving all users or not?

I think you're looking for `chunk`. `paginate` does not work the same as Laravel Eloquent models. `paginate` will attempt to return all results from your directory and keep them all in memory. `chunk` however, allows you to execute a callback over each chunk of users returned for each page of LDAP results in the query:

https://ldaprecord.com/docs/core/v3/searching/#chunking

```php
User::chunk(100, function ($users) {
     // ...
});
```

Let me know if this answers your question 👍

**Comment by fawwashkhan** [comment]
@stevebauman, Actually, I am trying to fetch more than 20,000 users from AD LDAP, and I want to implement pagination to retrieve them in chunks of 500 users at a time. My goal is to import all 20,000 users in increments like this: 1-500, 501-1000, 1001-1500, and so on, until I reach 20,000 users.

However, when I use the paginate method: 
```php
$pagedUsers = $provider->select('distinguishedname', 'givenname', 'name', 'objectguid', 'samaccountname', 'userprincipalname', 'mail')
->whereEnabled()
->paginate($pageSize, $this->currentPage);
``` 
it seems to be returning all 20,000 users at once instead of the expected 500 per page. This behavior is causing timeout issues, as I am trying to handle a large result set.

Additionally, I tried using a different search base that contains only 20 users and set the pagination size to 2. However, it still returned all 20 users instead of just 2 users per page. This further indicates that the pagination functionality is not working as expected.

I would appreciate any advice on how to properly implement pagination in this scenario to avoid loading all users at once.

**Comment by fawwashkhan** [comment]
@stevebauman As you suggested, using `chunk` works fine, but I've noticed that I still encounter timeout issues unless I set a timeout of 600 seconds (`public $timeout = 600;`). This is not a sustainable solution, especially if I need to fetch a larger dataset, like 100,000 users. I'm looking for a more efficient way to handle this without relying on extended timeouts.

**Comment by stevebauman** [comment]
> it seems to be returning all 20,000 users at once instead of the expected 500 per page. This behavior is causing timeout issues, as I am trying to handle a large result set.
>
> Additionally, I tried using a different search base that contains only 20 users and set the pagination size to 2. However, it still returned all 20 users instead of just 2 users per page. This further indicates that the pagination functionality is not working as expected.

Yes this is intended behaviour. `paginate` will return the entire result of a search.

> As you suggested, using chunk works fine, but I've noticed that I still encounter timeout issues unless I set a timeout of 600 seconds (public $timeout = 600;).

`$timeout` is being set on what? The command I presume? If you have a large directory, it will take time iterate through all of the chunks of a search request. If you want to keep the operation fast, you could instead disable recursive searches and dispatch a new job for every nested OU you encounter. This prevents you from retrieving all results at one time.

Since you're connecting to an Active Directory server, you may be looking for `slice`, which is another option in regards to safely iterating through a large directory:

https://ldaprecord.com/docs/core/v3/searching/#slicing

Though keep in mind that it has some caveats:

> Your query must search less than 10,000 total records (this is a [configurable limit](https://ldapwiki.com/wiki/MaxTempTableSize) in Active Directory).
